sudo: false
language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master
install:
  - go get -v -u github.com/nbio/st
  - go get -v -u github.com/client9/misspell/cmd/misspell
  - go get -v -u github.com/fzipp/gocyclo
  - go get -v -u github.com/golang/lint/golint
  - go get -v -u github.com/gordonklaus/ineffassign
  - go get -v -u github.com/kisielk/errcheck
  - go get -v -u github.com/mdempsky/unconvert
script:
  - go clean ./...
  - go vet ./...
  - errcheck -verbose -asserts ./...
  - unconvert -v .
  - gocyclo -over 10 ./
  - ineffassign ./
  - misspell -error ./* ./*/* ./*/*/* ./*/*/*/* ./*/*/*/*/* ./*/*/*/*/*/* ./*/*/*/*/*/*/*
  - go test -v ./...
  # - golint -set_exit_status ./...
